### ISSUE TITLE
Use Meteor.method to generate invoices

### ISSUE THREAD

**Issue by DominikGuzei** [Craphtex/invoice-example-application#1]
Currently you are generating the invoices on the client, which is a security issue and not performant.
In general avoid inserting documents directly on the client side, as it is regarded bad-practice in Meteor.
Let the client simply call a Meteor.method like this:

``` javascript
Template.DatabaseSetup.events({
  'click #generate': function () {
    Meteor.call('generate-invoices');
  }
});
```

and move the actually inserting logic to the server. Also try to use some batch-inserting instead of inserting each document individually (performance!)

**Comment by Craphtex** [comment]
Fixed in commit 35847c369efde3ede8185eeda38cc00148b795ee
