### ISSUE TITLE
Move subscriptions to the template that needs the data

### ISSUE THREAD

**Issue by DominikGuzei** [Craphtex/invoice-example-application#4]
Currently you are managing the invoices subscriptions in your buttons template – which should actually not know anything about invoices :wink: 

So your buttons code should look something like this:

``` javascript
'click #today': function () {
  Session.set('invoiceTimeRange', 'today');   
}
```

and let the `InvoiceTable` manage the subscription like this:

``` javascript
Template.InvoiceTable.onCreated({
  this.autorun(function() {
    this.subscribe('invoice-tickets', Session.get('invoiceTimeRange'), Session.get('invoiceSortBy'), Session.get('invoiceSortOrder'));
  });
});
```

the `autorun` will be automatically cleaned up when the template is destroyed etc. and the concrete query logic should only be on the server-side!

**Comment by Craphtex** [comment]
Will close this one, as it has been fixed since a while back.
