### ISSUE TITLE
Session vars are not reliable

### ISSUE THREAD

**Issue by DominikGuzei** [Craphtex/invoice-example-application#5]
You used session vars to "save" the latest invoice number `Session.setDefault('invoiceNumber', 1);`.
The biggest (immediate) problem with this approach is, that session vars do not survive page refreshing – so if the user reloads the page your session vars are all reset!

But anyway, best practice would be to move that code to the server-side and call it from the client via a Meteor.method :wink:

**Comment by Craphtex** [comment]
Fixed in commit 35847c369efde3ede8185eeda38cc00148b795ee
